# Generated by Django 6.0.6 on 2026-06-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_insured_value_alter_property_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('flooded_area_m2', models.FloatField(blank=True, null=True)),
                ('flooded_area_percent', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('recommendation', models.CharField(blank=True, choices=[('AUTO_APPROVE', 'Auto Approve'), ('MANUAL_REVIEW', 'Manual Review'), ('REJECT', 'Reject')], max_length=30)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='properties.property')),
            ],
        ),
    ]
