# Generated by Django 6.0.6 on 2026-06-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('AUTO_APPROVE', 'Auto Approve'), ('MANUAL_REVIEW', 'Manual Review'), ('AUTO_REJECT', 'Auto Reject')], max_length=30),
        ),
    ]
