# Generated by Django 6.0.6 on 2026-06-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='claims.claim'),
        ),
    ]
